import type { Metadata } from "next";
import { Nunito} from "next/font/google";
import "./globals.css";
import {Nav} from "@/components/Nav";
const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ImgAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black  text-white`}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
